# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 06:15
from __future__ import unicode_literals

import ICOToday.apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=40, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('alias', models.CharField(max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('type', models.IntegerField(choices=[(0, '需求方'), (1, '技术提供方')], default=0)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_verified', models.IntegerField(choices=[(0, '未通过'), (1, '审核中'), (2, '通过')], default=0)),
                ('is_company', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['created'],
            },
            managers=[
                ('objects', ICOToday.apps.accounts.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountVerifyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, null=True)),
                ('birthday', models.DateField(null=True)),
                ('working_at', models.CharField(max_length=50, null=True)),
                ('legal_id', models.FileField(upload_to='user_legal_id')),
                ('legal_id_type', models.IntegerField(choices=[(0, '中华人民共和国身份证'), (1, '护照'), (2, '驾照')], null=True)),
                ('wechat', models.CharField(max_length=50, null=True)),
                ('qq', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=20, null=True)),
                ('company_register_file', models.FileField(upload_to='company_register_file')),
                ('company_phone', models.CharField(max_length=50, null=True)),
                ('company_contact', models.CharField(max_length=50, null=True)),
                ('company_email', models.CharField(max_length=50, null=True)),
                ('company_address', models.CharField(max_length=50, null=True)),
                ('company_field', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verify_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('token', models.CharField(max_length=200)),
                ('expire_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
