# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifytoken',
            name='email',
        ),
        migrations.RemoveField(
            model_name='verifytoken',
            name='phone',
        ),
        migrations.AddField(
            model_name='verifytoken',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='verify_token', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
