# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170912_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(choices=[(0, b'ICO Company'), (1, b'ICO Investor')], default=0),
        ),
    ]
