# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_short', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Processing'), (1, 'Verified'), (2, 'Completed')], default=0)),
                ('prize', models.IntegerField()),
                ('due_date', models.DateTimeField(null=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('appliers', models.ManyToManyField(related_name='applied_questions', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_files/')),
                ('file_name', models.CharField(max_length=40)),
                ('file_size', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('type', models.IntegerField(choices=[(0, 'Industry'), (1, 'Tech')])),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='industry_tags',
            field=models.ManyToManyField(related_name='industry_questions', to='posts.QuestionTag'),
        ),
        migrations.AddField(
            model_name='post',
            name='marked',
            field=models.ManyToManyField(related_name='marked_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tech_tags',
            field=models.ManyToManyField(related_name='tech_questions', to='posts.QuestionTag'),
        ),
    ]
