# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 01:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ratingdescription',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ratingdescription',
            name='rater',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, b'Verifying'), (1, b'Verified'), (2, b'Completed'), (3, b'Promoting'), (4, b'Premium'), (5, b'Closed')], default=0),
        ),
        migrations.DeleteModel(
            name='RatingDescription',
        ),
        migrations.AddField(
            model_name='ratingdetail',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_detail', to='posts.Post'),
        ),
        migrations.AddField(
            model_name='ratingdetail',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
