# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170901_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='appliers',
            field=models.ManyToManyField(blank=True, related_name='applied_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='marked',
            field=models.ManyToManyField(blank=True, related_name='marked_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
